# Local overrides (Git ignored - safe for Atlas credentials)
spring.data.mongodb.uri=mongodb+srv://jaheerkalanthar816:E91qXKc7nQffvGB8@momoclus.7kcygv9.mongodb.net/personel_tracker?retryWrites=true&w=majority&appName=MomoClus
